import type { LearningWorld } from "../types/learning";

export const learningWorlds: LearningWorld[] = [
  {
    id: "world-1",
    title: "Stock Market Basics",
    description:
      "Build your foundation and understand how the stock market actually works.",
    order: 1,
    locked: false,
    completed: false,

    lessons: [
      {
        id: "lesson-1",
        worldId: "world-1",
        title: "What is the Stock Market?",
        description:
          "Understand what the stock market is and why companies issue shares.",
        concept: "Stock Market Basics",
        order: 1,
        xp: 100,
        completed: false,

        types: ["theory", "interactive", "quiz"],

        sections: [
          {
            title: "What is a Stock?",
            content:
              "A stock represents ownership in a company. When you buy a share, you become a small owner of that company.",
          },
          {
            title: "What is the Stock Market?",
            content:
              "The stock market is a marketplace where investors can buy and sell shares of publicly listed companies.",
          },
          {
            title: "Why do Companies Sell Shares?",
            content:
              "Companies can raise money from investors by issuing shares. Investors buy those shares because they expect the company to grow and potentially provide returns.",
          },
        ],
      },

      {
        id: "lesson-2",
        worldId: "world-1",
        prerequisiteLessonId: "lesson-1",
        title: "How Buying and Selling Works",
        description:
          "Learn how investors buy and sell stocks and how orders work.",
        concept: "Buying and Selling",
        order: 2,
        xp: 100,
        completed: false,

        types: ["theory", "interactive", "game", "quiz"],

        sections: [
          {
            title: "Buying a Stock",
            content:
              "When you buy a stock, you are purchasing shares of a company through a broker or trading platform.",
          },
          {
            title: "Selling a Stock",
            content:
              "When you sell a stock, you give up your shares in exchange for money at the available market price or your specified price.",
          },
          {
            title: "Your First Trading Decision",
            content:
              "Before buying or selling, investors should understand the company, price, risk and their investment objective.",
          },
        ],

        game: {
          id: "game-first-trade",
          title: "Your First Trade",
          description:
            "Make your first virtual investment and learn what happens when you buy and sell a stock.",
          concept: "Buy and Sell",
          type: "decision",
        },
      },
    ],
  },

  {
    id: "world-2",
    title: "Smart Investing",
    description:
      "Learn how to manage risk, build portfolios and make smarter investment decisions.",
    order: 2,
    locked: true,
    completed: false,

    lessons: [
      {
        id: "lesson-3",
        worldId: "world-2",
        title: "Risk and Return",
        description:
          "Understand the relationship between risk and potential return.",
        concept: "Risk and Return",
        order: 1,
        xp: 150,
        completed: false,

        types: ["theory", "interactive", "game", "quiz"],

        sections: [
          {
            title: "What is Risk?",
            content:
              "Investment risk is the possibility that an investment may produce a lower return than expected or lose value.",
          },
          {
            title: "What is Return?",
            content:
              "Return is the gain or loss generated by an investment over a period of time.",
          },
        ],

        game: {
          id: "game-risk-return",
          title: "Risk Commander",
          description:
            "Choose between different investments and discover how risk affects potential returns.",
          concept: "Risk and Return",
          type: "decision",
        },
      },

      {
        id: "lesson-4",
        worldId: "world-2",
        prerequisiteLessonId: "lesson-3",
        title: "Diversification",
        description:
          "Learn why putting all your money into one investment can be dangerous.",
        concept: "Diversification",
        order: 2,
        xp: 150,
        completed: false,

        types: ["theory", "interactive", "game", "simulation", "quiz"],

        sections: [
          {
            title: "What is Diversification?",
            content:
              "Diversification means spreading investments across different assets or sectors to reduce concentration risk.",
          },
          {
            title: "Why Diversify?",
            content:
              "Different investments may behave differently under the same market conditions. Diversification can help reduce the impact of a poor-performing investment on the overall portfolio.",
          },
        ],

        game: {
          id: "game-portfolio-builder",
          title: "Portfolio Builder",
          description:
            "Build a virtual portfolio and experience different market scenarios to understand diversification.",
          concept: "Diversification",
          type: "strategy",
        },
      },
    ],
  },

  {
    id: "world-3",
    title: "Fundamental Analysis",
    description:
      "Learn how investors study companies before deciding whether to invest.",
    order: 3,
    locked: true,
    completed: false,

    lessons: [
      {
        id: "lesson-5",
        worldId: "world-3",
        title: "Understanding Company Fundamentals",
        description:
          "Learn how to evaluate a company's financial health and business performance.",
        concept: "Fundamental Analysis",
        order: 1,
        xp: 200,
        completed: false,

        types: ["theory", "interactive", "game", "quiz"],

        sections: [
          {
            title: "What is Fundamental Analysis?",
            content:
              "Fundamental analysis involves studying a company's business, financial statements, industry and other factors to evaluate its value and prospects.",
          },
          {
            title: "What Should You Study?",
            content:
              "Investors may examine revenue, profit, debt, cash flow, earnings, profitability ratios, valuation and industry conditions.",
          },
        ],

        game: {
          id: "game-company-detective",
          title: "Company Detective",
          description:
            "Investigate companies using financial clues and decide which company appears stronger.",
          concept: "Fundamental Analysis",
          type: "analysis",
        },
      },
    ],
  },

  {
    id: "world-4",
    title: "Technical Analysis",
    description:
      "Learn how traders study price, volume and charts to make decisions.",
    order: 4,
    locked: true,
    completed: false,

    lessons: [
      {
        id: "lesson-6",
        worldId: "world-4",
        title: "Reading Candlestick Charts",
        description:
          "Learn how candlesticks represent price movement.",
        concept: "Candlesticks",
        order: 1,
        xp: 200,
        completed: false,

        types: ["theory", "interactive", "game", "quiz"],

        sections: [
          {
            title: "What is a Candlestick?",
            content:
              "A candlestick represents price movement during a specific time period and shows the open, high, low and close prices.",
          },
          {
            title: "Reading Price Action",
            content:
              "Candlestick patterns can help traders study market behaviour, although they should not be treated as guaranteed predictions of future prices.",
          },
        ],

        game: {
          id: "game-chart-detective",
          title: "Chart Detective",
          description:
            "Analyze historical charts, identify patterns and discover what happened next.",
          concept: "Candlestick Analysis",
          type: "analysis",
        },
      },
    ],
  },
];